name: test

on:
  push:

  schedule:     
    - cron: '*/3 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: get cake
        env:
          CAKE: ${{ secrets.CAKE }}
        run: |
          ls
          echo $(ls)
          echo $CAKE > cake
