name: test

on:
  push:

  schedule:     
    - cron: '*/3 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: get cake
        env:
          CAKE: ${{ secrets.CAKE }}
        run: |
          ls
          echo $(ls)
          echo $CAKE > cake
